### ISSUE TITLE
[BUG] Nothing is happening

### ISSUE THREAD

**Issue by jeff1193** [jackkerouac/aphrodite#60]
Hi,

I juste did this : 
# 1. Download files
mkdir aphrodite && cd aphrodite
curl -L https://github.com/jackkerouac/aphrodite/releases/latest/download/docker-compose.yml -o docker-compose.yml
curl -L https://github.com/jackkerouac/aphrodite/releases/latest/download/.env.example -o .env

# 2. Edit .env (optional - secure defaults provided)
nano .env

# 3. Start services
docker-compose up -d

nothing happend, 
when i'm looking at theses files :
- docker-compose.yml -> nothing inside (getting a NOT FOUND)
- .env -> nothing inside, same as before

Well, did i missed something ?

**Comment by jeff1193** [comment]
@jackkerouac Any News ?

**Comment by jackkerouac** [comment]
Try again. There was an issue where the files were empty, but they should be fixed now. You can also cut-and-paste the content of the files from source, if you don't want to curl again.

**Comment by jeff1193** [comment]
> Try again. There was an issue where the files were empty, but they should be fixed now. You can also cut-and-paste the content of the files from source, if you don't want to curl again.

Hello,
nop, still not working.

I did the same and apparently "password authentification failed for user aphrodite"

i change the password in the .env, like in the description.

**Comment by jackkerouac** [comment]
Ah. This can happen if you change the password for the database after setting it up. You can do one of two things: 1. Delete the database and start over, or change your password back to what it was.

**Comment by jeff1193** [comment]
Well...the problem is...i didn't change the password...
user is 
aphrodite
password is the same :/

each time i test, i'm deleting the dockers

**Comment by jackkerouac** [comment]
When you run `docker-compose up -d` again, PostgreSQL reuses the existing database with the old password, even though you changed the .env file.

You need to delete the database volume, not just the containers.

```
# Navigate to your aphrodite directory
cd aphrodite

# Stop and remove containers AND volumes (this deletes the database)
docker-compose down --volumes

# Verify volumes are gone
docker volume ls | grep aphrodite

# Now start fresh with your new password
docker-compose up -d

# Check if services are starting correctly
docker-compose logs -f
```

If the above doesn't work:

```
# Remove everything related to this project
docker-compose down --volumes --rmi all

# Remove any remaining volumes manually
docker volume rm $(docker volume ls -q | grep aphrodite) 2>/dev/null || true

# Start completely fresh
docker-compose up -d
```

When you run docker-compose down (without --volumes), Docker:

1. Stops and removes containers
2. Keeps the database volume with the old password

PostgreSQL only sets the password on first initialization. If the database already exists (from the previous run), it ignores the new password in the .env file.

After the reset, you can verify it worked by checking the logs:

`docker-compose logs postgres`

You should see messages about database initialization, not "database already exists" messages.

**Comment by jeff1193** [comment]
Ok, i did what you wrote but i still get this : 

![Image](https://github.com/user-attachments/assets/a971dc5e-3ec7-4f58-a580-3d4b90e82a04)
error for this aphrodite user...


do i need to change something into the docker-compose.yml ? 
because i'm only changing these things into the .env 

POSTGRES_PASSWORD=somethinghere
SECRET_KEY=somethingwithalotofcharactershere==

and if i'm doign this : 

![Image](https://github.com/user-attachments/assets/a2514a1b-7249-4b6f-94b4-417c737c175c)

apparently, it's good...what the hell ? 💃

**Comment by jackkerouac** [comment]
Okay, I did some more investigation here (your screenshots were invaluable, BTW).

The issue was in the docker-compose.yml file. The application code is 'smart' - it tries to build the database connection from individual environment variables like `POSTGRES_HOST, POSTGRES_USER, POSTGRES_PASSWORD`, etc. But if it doesn't find *ALL* of them, it falls back to a hard-coded default database URL that still had the old password "changeme".

The `docker-compose.yml` was missing `POSTGRES_HOST` and `POSTGRES_PORT` environment variables, so even though you set `POSTGRES_PASSWORD` in your `.env` file, the app couldn't use it because it didn't have the complete set of database variables.

There are two ways to fix this:

**Option 1 (Recommended): Download the updated files**
```
cd aphrodite
# Stop everything first
docker compose down --volumes

# Download the fixed docker-compose.yml
curl -L https://github.com/jackkerouac/aphrodite/releases/latest/download/docker-compose.yml -o docker-compose.yml

# Make sure your .env has your password set
nano .env

# Start fresh
docker compose up -d
```

**Option 2: Manual fix to your existing docker-compose.yml**
Add these two lines to the environment section of both the aphrodite and aphrodite-worker services:
```
POSTGRES_HOST: postgres
POSTGRES_PORT: 5432
```

Then:

```
docker compose down --volumes
docker compose up -d
```

The key thing is that **--volumes** flag - that's what actually deletes the database with the old password. Without it, PostgreSQL keeps using the existing database even if you change the password in `.env`.

The application *should* now properly read your custom password from the environment variables instead of falling back to the hard-coded default.

**Comment by jeff1193** [comment]
Hi,

It's working now !
BUT
Not totally, the preview is showing nothing
No badges (I have nothing on the poster, all is good in the settings I
guess)
I can't either manually add them (into the poster manager section, it
saying all good, but nothing is changing..)

And last thing : when I'm Trying to force a schedules,  it saying
"pending" but nothing is starting..

Any help ?


Le lun. 30 juin 2025, 00:32, Jack Kerouac ***@***.***> a
écrit :

**Comment by jackkerouac** [comment]
You will have to post your logs on the Preview page so I can see what's going on. I will look into the scheduling function.

**Comment by jeff1193** [comment]
Hi,

My issue is exactly the same as the #64
Same logs

The schedule pending, etc...

Le lun. 30 juin 2025, 15:29, Jack Kerouac ***@***.***> a
écrit :

**Comment by jeff1193** [comment]
i'm closing this for opening a new one, cause the original problem was fixed
